var resCfg = cc.resCfg;
var jsRes = js.cocos2d-html5;

resCfg["cocos2d-html5"] = {
    ref : [
        jsRes.CCClass_js,
        jsRes.CCGeometry_js,
        jsRes.Sys_js,
        jsRes.CCConfig_js,
        jsRes.miniFramework_js,
        jsRes.CCCommon_js,
        jsRes.CCMacro_js,
        jsRes.CCFileUtils_js,
        jsRes.CCTypes_js,
        jsRes.CCEGLView_js,
        jsRes.CCScreen_js,
        jsRes.CCVisibleRect_js,
        jsRes.CCNS_js,
        jsRes.CCAffineTransform_js,
        jsRes.CCPointExtension_js,
        jsRes.CCVertex_js,
        jsRes.TransformUtils_js,
        jsRes.CCNode_js,
        jsRes.CCAtlasNode_js,
        jsRes.CCTexture2D_js,
        jsRes.CCTextureCache_js,
        jsRes.CCTextureAtlas_js,
        jsRes.CCScene_js,
        jsRes.CCLayer_js,
        jsRes.CCSprite_js,
        jsRes.CCAnimation_js,
        jsRes.CCAnimationCache_js,
        jsRes.CCSpriteFrame_js,
        jsRes.CCSpriteFrameCache_js,
        jsRes.CCSpriteBatchNode_js,
        jsRes.CCConfiguration_js,
        jsRes.CCDirector_js,
        jsRes.CCCamera_js,
        jsRes.CCScheduler_js,
        jsRes.CCLoader_js,
        jsRes.CCApplication_js,
        jsRes.CCSAXParser_js,
        jsRes.AppControl_js
    ]//Base references for the project.
};