var cc = cc || {};
cc.resCfg = cc.resCfg || {};

/**
 * cc.resCfg[js.cocos2d_html5.a_js] = {ref : [], res : []}
 */

var resCfg = cc.resCfg;

//base for core module
resCfg["cocos2d-html5"] = {
    ref : [
        js.cocos2d_html5.CCClass_js,
        js.cocos2d_html5.CCGeometry_js,
        js.cocos2d_html5.Sys_js,
        js.cocos2d_html5.CCConfig_js,
        js.cocos2d_html5.miniFramework_js,
        js.cocos2d_html5.CCCommon_js,
        js.cocos2d_html5.CCMacro_js,
        js.cocos2d_html5.CCFileUtils_js,
        js.cocos2d_html5.CCTypes_js,
        js.cocos2d_html5.CCEGLView_js,
//        js.cocos2d_html5.CCImage_js,
//        js.cocos2d_html5.CCScreen_js,
        js.cocos2d_html5.CCVisibleRect_js,
//        js.cocos2d_html5.utility_js,
//        js.cocos2d_html5.vec2_js,
//        js.cocos2d_html5.vec3_js,
//        js.cocos2d_html5.vec4_js,
//        js.cocos2d_html5.ray2_js,
//        js.cocos2d_html5.mat3_js,
//        js.cocos2d_html5.mat4_js,
//        js.cocos2d_html5.plane_js,
//        js.cocos2d_html5.quaternion_js,
//        js.cocos2d_html5.aabb_js,
//        js.cocos2d_html5.mat4stack_js,
//        js.cocos2d_html5.matrix_js,
        js.cocos2d_html5.CCNS_js,
        js.cocos2d_html5.CCAffineTransform_js,
        js.cocos2d_html5.CCPointExtension_js,
        js.cocos2d_html5.CCVertex_js,
        js.cocos2d_html5.TransformUtils_js,
        js.cocos2d_html5.CCComponent_js,
        js.cocos2d_html5.CCComponentContainer_js,
//        js.cocos2d_html5.CCShaders_js,
//        js.cocos2d_html5.CCShaderCache_js,
//        js.cocos2d_html5.CCGLProgram_js,
//        js.cocos2d_html5.CCGLStateCache_js,
        js.cocos2d_html5.CCNode_js,
        js.cocos2d_html5.CCAtlasNode_js,
        js.cocos2d_html5.CCTexture2D_js,
        js.cocos2d_html5.CCTextureCache_js,
        js.cocos2d_html5.CCTextureAtlas_js,
//        js.cocos2d_html5.CCRenderTexture_js,
//        js.cocos2d_html5.CCProgressTimer_js,
        js.cocos2d_html5.CCDrawNode_js,
        js.cocos2d_html5.CCAction_js,
        js.cocos2d_html5.CCActionInterval_js,
        js.cocos2d_html5.CCActionInstant_js,
        js.cocos2d_html5.CCActionManager_js,
//        js.cocos2d_html5.CCActionProgressTimer_js,
//        js.cocos2d_html5.CCActionCamera_js,
        js.cocos2d_html5.CCActionEase_js,
        js.cocos2d_html5.CCActionCatmullRom_js,
//        js.cocos2d_html5.CCActionTween_js,
        js.cocos2d_html5.CCScene_js,
        js.cocos2d_html5.CCLayer_js,
        js.cocos2d_html5.CCSprite_js,
        js.cocos2d_html5.CCSpriteFrame_js,
        js.cocos2d_html5.CCSpriteFrameCache_js,
        js.cocos2d_html5.CCSpriteBatchNode_js,
        js.cocos2d_html5.CCLabelTTF_js,
        js.cocos2d_html5.CCTouchDelegateProtocol_js,
        js.cocos2d_html5.CCTouchHandler_js,
        js.cocos2d_html5.CCTouchDispatcher_js,
        js.cocos2d_html5.CCConfiguration_js,
        js.cocos2d_html5.CCDirector_js,
        js.cocos2d_html5.CCCamera_js,
        js.cocos2d_html5.CCScheduler_js,
        js.cocos2d_html5.CCLoader_js,
        js.cocos2d_html5.CCDrawingPrimitives_js,
        js.cocos2d_html5.CCApplication_js,
        js.cocos2d_html5.CCSAXParser_js,
        js.cocos2d_html5.AppControl_js,
        js.cocos2d_html5.CCMenuItem_js,
        js.cocos2d_html5.CCMenu_js
    ]
};
